# Generated by Django 4.2 on 2023-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_Content',
            field=models.TextField(default=''),
        ),
    ]
