# Generated by Django 4.2 on 2023-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='No_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
